### PR TITLE
Dynamic list item loading

### LINKED ISSUE #75: C2-12828-1 crash when clicking Download button for any homebrew
```
VHBB started.
- Version: 00.91
- Commit: ca81c8c495ede05c2f64af9fdd8d1434d9ba49bb
- GitHub: https://github.com/devnoname120/vhbb/tree/ca81c8c495ede05c2f64af9fdd8d1434d9ba49bb
- OS: 3.65

[/home/devnoname120/psv/vhbb/src/vitaPackage.cpp:199 VitaPackage::VitaPackage()]  Loading PAF
[/home/devnoname120/psv/vhbb/src/vitaPackage.cpp:213 VitaPackage::~VitaPackage()]  Unloading PAF
[/home/devnoname120/psv/vhbb/src/network.cpp:208 Network::TestConnection()]  Content length: 8
[/home/devnoname120/psv/vhbb/src/update.cpp:91 Update::getVersionInfo()]  sceIoRemove(ux0:/data/VitaHbBrowser/latest_version.yml) = 0x80010002
[/home/devnoname120/psv/vhbb/src/network.cpp:109 Network::Download()]  Downloading https://vhbb.download/version.php to ux0:/data/VitaHbBrowser/latest_version.yml
[/home/devnoname120/psv/vhbb/src/network.cpp:162 Network::Download()]  Done downloading https://vhbb.download/version.php
[/home/devnoname120/psv/vhbb/src/update.cpp:77 readVersionYAML()]  Version field successfully parsed 0 91
[/home/devnoname120/psv/vhbb/src/update.cpp:112 Update::getVersionInfo()]  Latest online version: 00.91
[/home/devnoname120/psv/vhbb/src/update.cpp:129 Update::getVersionInfo()]  Current version 00.91 is up-to-date
[/home/devnoname120/psv/vhbb/src/network.cpp:109 Network::Download()]  Downloading https://rinnegatamante.it/vitadb/list_hbs_yaml.php to ux0:/data/VitaHbBrowser/homebrews.yaml
[/home/devnoname120/psv/vhbb/src/network.cpp:162 Network::Download()]  Done downloading https://rinnegatamante.it/vitadb/list_hbs_yaml.php
[/home/devnoname120/psv/vhbb/src/Views/ListView/listView.cpp:88 ListView::ListView()]  posY: 0
[/home/devnoname120/psv/vhbb/src/Views/ListView/listView.cpp:89 ListView::ListView()]  homebrews size: 315
[/home/devnoname120/psv/vhbb/src/Views/ListView/listView.cpp:88 ListView::ListView()]  posY: 0
[/home/devnoname120/psv/vhbb/src/Views/ListView/listView.cpp:89 ListView::ListView()]  homebrews size: 89
[/home/devnoname120/psv/vhbb/src/Views/ListView/listView.cpp:88 ListView::ListView()]  posY: 0
[/home/devnoname120/psv/vhbb/src/Views/ListView/listView.cpp:89 ListView::ListView()]  homebrews size: 80
[/home/devnoname120/psv/vhbb/src/Views/ListView/listView.cpp:88 ListView::ListView()]  posY: 0
[/home/devnoname120/psv/vhbb/src/Views/ListView/listView.cpp:89 ListView::ListView()]  homebrews size: 18
[/home/devnoname120/psv/vhbb/src/Views/ListView/listView.cpp:88 ListView::ListView()]  posY: 0
[/home/devnoname120/psv/vhbb/src/Views/ListView/listView.cpp:89 ListView::ListView()]  homebrews size: 128
[/home/devnoname120/psv/vhbb/src/Views/ListView/listView.cpp:88 ListView::ListView()]  posY: 0
[/home/devnoname120/psv/vhbb/src/Views/ListView/listView.cpp:89 ListView::ListView()]  homebrews size: 315
[/home/devnoname120/psv/vhbb/src/Views/CategoryView/categoryView.cpp:93 CategoryView::CategoryView()]  Done tabs creation
[/home/devnoname120/psv/vhbb/src/Views/CategoryView/categoryView.cpp:142 CategoryView::selectCat()]  selectCat(unsigned 0)
[/home/devnoname120/psv/vhbb/src/Views/CategoryView/categoryView.cpp:148 CategoryView::selectCat()]  selectCat(unsigned) 0->SignalSelected()
[/home/devnoname120/psv/vhbb/src/Views/ListView/listView.h:24 ListView::SignalSelected()]  ListView::SignalSelected
[/home/devnoname120/psv/vhbb/src/Views/CategoryView/categoryView.cpp:108 CategoryView::CategoryView()]  countAutoWidth 5
[/home/devnoname120/psv/vhbb/src/Views/CategoryView/categoryView.cpp:131 CategoryView::CategoryView()]  0->minX=0
[/home/devnoname120/psv/vhbb/src/Views/CategoryView/categoryView.cpp:132 CategoryView::CategoryView()]  0->maxX=176
[/home/devnoname120/psv/vhbb/src/Views/CategoryView/categoryView.cpp:133 CategoryView::CategoryView()]  remainingWidth=0
[/home/devnoname120/psv/vhbb/src/Views/CategoryView/categoryView.cpp:131 CategoryView::CategoryView()]  1->minX=176
[/home/devnoname120/psv/vhbb/src/Views/CategoryView/categoryView.cpp:132 CategoryView::CategoryView()]  1->maxX=352
[/home/devnoname120/psv/vhbb/src/Views/CategoryView/categoryView.cpp:133 CategoryView::CategoryView()]  remainingWidth=0
[/home/devnoname120/psv/vhbb/src/Views/CategoryView/categoryView.cpp:131 CategoryView::CategoryView()]  2->minX=352
[/home/devnoname120/psv/vhbb/src/Views/CategoryView/categoryView.cpp:132 CategoryView::CategoryView()]  2->maxX=528
[/home/devnoname120/psv/vhbb/src/Views/CategoryView/categoryView.cpp:133 CategoryView::CategoryView()]  remainingWidth=0
[/home/devnoname120/psv/vhbb/src/Views/CategoryView/categoryView.cpp:131 CategoryView::CategoryView()]  3->minX=528
[/home/devnoname120/psv/vhbb/src/Views/CategoryView/categoryView.cpp:132 CategoryView::CategoryView()]  3->maxX=704
[/home/devnoname120/psv/vhbb/src/Views/CategoryView/categoryView.cpp:133 CategoryView::CategoryView()]  remainingWidth=0
[/home/devnoname120/psv/vhbb/src/Views/CategoryView/categoryView.cpp:131 CategoryView::CategoryView()]  4->minX=704
[/home/devnoname120/psv/vhbb/src/Views/CategoryView/categoryView.cpp:132 CategoryView::CategoryView()]  4->maxX=880
[/home/devnoname120/psv/vhbb/src/Views/CategoryView/categoryView.cpp:133 CategoryView::CategoryView()]  remainingWidth=0
[/home/devnoname120/psv/vhbb/src/Views/CategoryView/categoryView.cpp:131 CategoryView::CategoryView()]  5->minX=880
[/home/devnoname120/psv/vhbb/src/Views/CategoryView/categoryView.cpp:132 CategoryView::CategoryView()]  5->maxX=960
[/home/devnoname120/psv/vhbb/src/Views/CategoryView/categoryView.cpp:133 CategoryView::CategoryView()]  remainingWidth=0
[/home/devnoname120/psv/vhbb/src/Views/ListView/listView.cpp:178 ListView::HandleInput()]  lastFullyDisplayedItem(): 4
[/home/devnoname120/psv/vhbb/src/Views/ListView/listView.cpp:184 ListView::HandleInput()]  Pressed, adding view...
[/home/devnoname120/psv/vhbb/src/network.cpp:109 Network::Download()]  Downloading https://rinnegatamante.it/vitadb/screenshots/439b029308191ea333ae11a513516cbc7802a0cbbb948917f90be57454147fd5.png to ux0:/data/VitaHbBrowser/screenshots/439b029308191ea333ae11a513516cbc7802a0cbbb948917f90be57454147fd5.png
[/home/devnoname120/psv/vhbb/src/network.cpp:162 Network::Download()]  Done downloading https://rinnegatamante.it/vitadb/screenshots/439b029308191ea333ae11a513516cbc7802a0cbbb948917f90be57454147fd5.png
[/home/devnoname120/psv/vhbb/src/texture.cpp:13 DeleteTexture()]  Destroying texture...
[/home/devnoname120/psv/vhbb/src/Views/HomebrewView/homebrewView.cpp:62 HomebrewView::HomebrewView()]  Checking if installed
[/home/devnoname120/psv/vhbb/src/homebrew.cpp:25 Homebrew::IsInstalled()]  Checking if QUAK00001 exists...
[/home/devnoname120/psv/vhbb/src/homebrew.cpp:27 Homebrew::IsInstalled()]  Done checking
[/home/devnoname120/psv/vhbb/src/Views/HomebrewView/homebrewView.cpp:108 HomebrewView::checkInstalled()]  installed_ = 1
[/home/devnoname120/psv/vhbb/src/input.cpp:221 Input::TouchInRectangle()]  TouchInRectangle rectangle: 218.000000,198.000000:371.000000,244.000000
[/home/devnoname120/psv/vhbb/src/input.cpp:222 Input::TouchInRectangle()]  TouchInRectangle touch: 298.655550,224.706532
[/home/devnoname120/psv/vhbb/src/shapes.cpp:12 Rectangle::Inside()]  Inside point: 298.655550,224.706532
[/home/devnoname120/psv/vhbb/src/Views/HomebrewView/homebrewView.cpp:118 HomebrewView::HandleInput()]  Touch in rectangle for install
[/home/devnoname120/psv/vhbb/src/Views/HomebrewView/homebrewView.cpp:95 HomebrewView::homebrewInstall()]  OK
[/home/devnoname120/psv/vhbb/src/network.cpp:109 Network::Download()]  Downloading https://bintray.com/vitadb/VitaDB/download_file?file_path=Homebrews+Data+Files%2FvitaQuake.zip to ux0:/temp/data.zip 
```

At this point the app crashes. It used to work fine before, but now crashes on both psv1000 and psv2000 without any changes on the devices (no new plug-ins or updates).

Core dump: https://dl.dropboxusercontent.com/s/veew5h41rccs14h/core.zip.

3.65 enso, plugins `config.txt`:

```
# This file is used as an alternative if ux0:tai/config.txt is not found.
# For users plugins, you must refresh taiHEN from HENkaku Settings for
# changes to take place.
# For kernel plugins, you must reboot for changes to take place.
*KERNEL
ur0:tai/storagemgr.skprx
ux0:app/PSPEMUCFW/sce_module/adrenaline_kernel.skprx
ur0:tai/custom_boot_splash.skprx
ur0:tai/lolicon.skprx
ur0:tai/nonpdrm_un.skprx
ur0:tai/nopsmdrm.skprx
ur0:tai/repatch.skprx
ur0:tai/reF00D.skprx
ur0:tai/noled.skprx
ur0:tai/ioplus.skprx
# henkaku.skprx is hard-coded to load and is not listed here
*main
ur0:tai/nolockscreen.suprx
ur0:tai/custom_warning.suprx
ur0:tai/shellbat.suprx
# main is a special titleid for SceShell
ur0:tai/henkaku.suprx
*NPXS10015
# this is for modifying the version string
ur0:tai/henkaku.suprx
*NPXS10016
# this is for modifying the version string in settings widget
ur0:tai/henkaku.suprx
*ALL
ur0:tai/itls.suprx
```

Uninstalling vhbb and cleaning all its folders,, then reinstalling didn't help. Other homebrews still work without issues.

### PR DESCRIPTION
**Pull request by robsdedude**
This fixes #75 but it makes the search more fragile.  
Feel free to play around with `PRE_RENDER_EXTRA_LIST_ITEM` and `MAX_LOAD_LIST_ITEMS_PER_CYCLE` in `src/Views/ListView/listView.h`. They will modify the smoothness of scrolling and the memory footprint.

Now about the search. Things I found out:
 - It currently crashes when you filter with broad terms. Do a search with "a", then "e", then "i", etc. Eventually it will crash exactly when you try to open the search window. I wasn't able to figure out why this happens. But it's certainly better to have a sometimes crashing search than an always crashing app.
 - The search also crashes on the master version, it's just harder to get it to crash. You'll need more searches until it breaks.
 - Commenting out `src/Views/ListView/searchView.cpp` lines 34-43 (which as expected makes the search do nothing but always show all homebrews) seems to fix the crashing.

Thus, I assume it is a memory leak or so, but I couldn't find a way to fix it. Sorry, I'm still not a c/c++ developer :man_shrugging:. Maybe you could have a look and find what's wrong.

PS: I marked it as WIP because of the search issue. Feel free to merge it anyway, if you want a hotfix. I won't continue the bug hunt until I have new input on this.

### CODE REVIEW

**Comment by robsdedude** [comment]
You might notice that, in contrast to what I wrote in my [comment](https://github.com/devnoname120/vhbb/issues/75#issuecomment-599846826), you can see the list items load now. This is a recent change I made that makes the scrolling smoother. If you prefer the previous behavior (i.e. lagging scrolling but no missing list items) try setting `MAX_LOAD_LIST_ITEMS_PER_CYCLE` to something like 7 I guess.

File: src/Views/ListView/searchView.cpp [hunk 1]
```diff
@@ -34,11 +34,13 @@ int SearchView::Display()
...
-            listItems.clear();
-            for (Homebrew hb : hbs)
-            {
-                listItems.emplace_back(hb);
+            homebrews = hbs;
+            for (ListItem* item: listItems) {
+                delete item;
             }
+            listItems.clear();
+            listItems = std::vector<ListItem*>(homebrews.size(), nullptr);
```
Comment (devnoname120) [inline src/Views/ListView/searchView.cpp]: So this won't be necessary anymore. You can add a `listItems.reserve(homebrews.size())` to make sure we have predictable perfs.

**Comment by robsdedude** [comment]
Have you tried it out with increased heap size already?

**Comment by devnoname120** [comment]
Sorry for the late reply I thought that I had replied already. Yes I tried it and it didn't solve the issue. I've also tried to increase stack size without luck.

I have no idea why your fix works, but it's great that it does!
